version: '3.8'

services:
  chat-service:
    build: .
    image: chat-service:0.1
    container_name: chat-service
    ports:
      - 8000:8000
    networks:
      - chat-network

  mongodb:
    image: mongo:6.0.4
    container_name: monogdb
    networks:
      - chat-network
  
networks:
  chat-network:
    name: chat-network