version: '3.8'

services:
  chat-service:
    build: .
    image: chat-service:0.1
    container_name: chat-service
    ports:
      - 8000:8000
    networks:
      - docker-services-net
  
networks:
  docker-services-net:
    name: docker-services-net